<a href="https://colab.research.google.com/github/kamilsielski-py/data-science-bootcamp/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
### NUMPY

In [ ]:
import numpy as np


In [ ]:
np.__version__ # wersja numpy

'1.19.5'

In [ ]:
dir(np) # wszystkie atrybuty i metody

In [ ]:
# wyswietlenie pomocy


In [ ]:
help(np.array)

In [ ]:
# 1 D ARRAY

In [ ]:
x = np.array([1, 3, 5])
x

array([1, 3, 5])

In [10]:
# typ

In [11]:
type(x) 

numpy.ndarray

In [12]:
# wymiar tablic i ksztalt

In [15]:
x.ndim


1

In [16]:
x.shape

(3,)

In [17]:
# rozmiar

In [18]:
x.size

3

In [19]:
# typ danych
x.dtype

dtype('int64')

In [21]:
x = np.array([1.1, 1.2, 1.3])

In [22]:
print(x)

[1.1 1.2 1.3]


In [23]:
x.dtype

dtype('float64')

In [24]:
## 2D ARRAY

In [28]:
x = np.array([[1,2], [-3, 1]])

In [29]:
x.ndim

2

In [30]:
x.shape

(2, 2)

In [31]:
x = np.array([[1, 4, 5], [5, 6, 8]])

In [32]:
x.shape

(2, 3)

In [33]:
# 3 D ARRAY


In [37]:
x = np.array([[[4, 3, 1],
               [3, 6, 6]],
              
              [[4, 4, 4],
              [4, 2, 1]],
]
)

In [38]:
print(x)

[[[4 3 1]
  [3 6 6]]

 [[4 4 4]
  [4 2 1]]]


In [39]:
x.ndim

3

In [40]:
### PODSTAWOWE TYPY DANYCH W NUMPY

In [41]:
A = np.array([ 1, 2, 2])
A.dtype

dtype('int64')

In [42]:
A = np.array([ 1.3, 2.3, 2])

In [43]:
A.dtype

dtype('float64')

In [44]:
A = np.array([ 1, 2, 2], dtype=float)

In [45]:
A.dtype

dtype('float64')

In [46]:
#### TWORZENIE TABLIC


In [47]:
np.zeros(shape=(4, 10)) # tablica skadajaca sie z samych zer

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [49]:
np.ones(shape=(5,5)) # tablica z jedynkami

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [50]:
np.full(shape=(3,3), fill_value=4, dtype='int') # wypelnieni tablicy konkretna wartoscia

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [51]:
np.arange(210)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [53]:
np.arange(start=5, stop=210, step=5)

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125, 130,
       135, 140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190, 195,
       200, 205])

In [57]:
np.arange(start=210, stop=100, step=-10)

array([210, 200, 190, 180, 170, 160, 150, 140, 130, 120, 110])

In [58]:
np.linspace(start=0, stop=1, num=10) # 10 rowno rozlozonych elementow z tego zakresu

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [59]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [63]:
B = A.reshape(3, 5) # zmiana rozmiaru tablicy

In [64]:
B

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [65]:
A.reshape(-1, 3) # -1 dobranie automatyczne parametru

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [66]:
#### PODSTAWOWE OPERACJE NA TABLICACH ####

In [67]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])

In [68]:
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [69]:
A + B # liczba elementow musi sie zgadzac


array([6, 0, 7, 4])

In [70]:
A-B

array([0, 2, 1, 0])

In [71]:
A*B

array([ 9, -1, 12,  4])

In [72]:
A/B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [73]:
A + 3 # dodamy 3 do kazdego elementu

array([6, 4, 7, 5])

In [74]:
A + 3 * B

array([12, -2, 13,  8])

In [75]:
# metody

In [77]:
np.add(A, B) # dodawanie tablic

array([6, 0, 7, 4])

In [79]:
np.subtract(A, B)

array([0, 2, 1, 0])

In [80]:
np.multiply(A, B)

array([ 9, -1, 12,  4])

In [81]:
np.divide(A, B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [82]:
### MNOZENIE MACIERZOWE

In [85]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])

print(X)
print(Y)

[[ 1  3]
 [-2  0]]
[[ 6  0]
 [-1  2]]


In [84]:
np.dot( X, Y) # mnozenie wiersz razy kolumna

array([[  3,   6],
       [-12,   0]])

In [86]:
X.dot(Y) # mnozenie macierzy nie jest przemienne

array([[  3,   6],
       [-12,   0]])

In [87]:
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])

In [88]:
X @ Y

array([[  3,   6],
       [-12,   0]])

In [89]:
#### Array: Generowanie liczb pseudolosowych - np.random


In [91]:
np.random.seed(0) # ziarno losowania, za kazdym razym uzyskamy ten sam wynik losowania