<a href="https://colab.research.google.com/github/kamilsielski-py/data-science-bootcamp/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
### NUMPY

In [ ]:
import numpy as np


In [ ]:
np.__version__ # wersja numpy

'1.19.5'

In [ ]:
dir(np) # wszystkie atrybuty i metody

In [ ]:
# wyswietlenie pomocy


In [ ]:
help(np.array)

In [ ]:
# 1 D ARRAY

In [ ]:
x = np.array([1, 3, 5])
x

array([1, 3, 5])

In [10]:
# typ

In [11]:
type(x) 

numpy.ndarray

In [12]:
# wymiar tablic i ksztalt

In [15]:
x.ndim


1

In [16]:
x.shape

(3,)

In [17]:
# rozmiar

In [18]:
x.size

3

In [19]:
# typ danych
x.dtype

dtype('int64')

In [21]:
x = np.array([1.1, 1.2, 1.3])

In [22]:
print(x)

[1.1 1.2 1.3]


In [23]:
x.dtype

dtype('float64')

In [24]:
## 2D ARRAY

In [28]:
x = np.array([[1,2], [-3, 1]])

In [29]:
x.ndim

2

In [30]:
x.shape

(2, 2)

In [31]:
x = np.array([[1, 4, 5], [5, 6, 8]])

In [32]:
x.shape

(2, 3)

In [33]:
# 3 D ARRAY


In [37]:
x = np.array([[[4, 3, 1],
               [3, 6, 6]],
              
              [[4, 4, 4],
              [4, 2, 1]],
]
)

In [38]:
print(x)

[[[4 3 1]
  [3 6 6]]

 [[4 4 4]
  [4 2 1]]]


In [39]:
x.ndim

3

In [40]:
### PODSTAWOWE TYPY DANYCH W NUMPY

In [41]:
A = np.array([ 1, 2, 2])
A.dtype

dtype('int64')

In [42]:
A = np.array([ 1.3, 2.3, 2])

In [43]:
A.dtype

dtype('float64')

In [44]:
A = np.array([ 1, 2, 2], dtype=float)

In [45]:
A.dtype

dtype('float64')

In [46]:
#### TWORZENIE TABLIC


In [47]:
np.zeros(shape=(4, 10)) # tablica skadajaca sie z samych zer

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [49]:
np.ones(shape=(5,5)) # tablica z jedynkami

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [50]:
np.full(shape=(3,3), fill_value=4, dtype='int') # wypelnieni tablicy konkretna wartoscia

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [51]:
np.arange(210)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [53]:
np.arange(start=5, stop=210, step=5)

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125, 130,
       135, 140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190, 195,
       200, 205])

In [57]:
np.arange(start=210, stop=100, step=-10)

array([210, 200, 190, 180, 170, 160, 150, 140, 130, 120, 110])

In [58]:
np.linspace(start=0, stop=1, num=10) # 10 rowno rozlozonych elementow z tego zakresu

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [59]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [63]:
B = A.reshape(3, 5) # zmiana rozmiaru tablicy

In [64]:
B

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [65]:
A.reshape(-1, 3) # -1 dobranie automatyczne parametru

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [66]:
#### PODSTAWOWE OPERACJE NA TABLICACH ####

In [67]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])

In [68]:
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [69]:
A + B # liczba elementow musi sie zgadzac


array([6, 0, 7, 4])

In [70]:
A-B

array([0, 2, 1, 0])

In [71]:
A*B

array([ 9, -1, 12,  4])

In [72]:
A/B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [73]:
A + 3 # dodamy 3 do kazdego elementu

array([6, 4, 7, 5])

In [74]:
A + 3 * B

array([12, -2, 13,  8])

In [75]:
# metody

In [77]:
np.add(A, B) # dodawanie tablic

array([6, 0, 7, 4])

In [79]:
np.subtract(A, B)

array([0, 2, 1, 0])

In [80]:
np.multiply(A, B)

array([ 9, -1, 12,  4])

In [81]:
np.divide(A, B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [82]:
### MNOZENIE MACIERZOWE

In [85]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])

print(X)
print(Y)

[[ 1  3]
 [-2  0]]
[[ 6  0]
 [-1  2]]


In [84]:
np.dot( X, Y) # mnozenie wiersz razy kolumna

array([[  3,   6],
       [-12,   0]])

In [86]:
X.dot(Y) # mnozenie macierzy nie jest przemienne

array([[  3,   6],
       [-12,   0]])

In [87]:
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])

In [88]:
X @ Y

array([[  3,   6],
       [-12,   0]])

In [89]:
#### Array: Generowanie liczb pseudolosowych - np.random


In [91]:
np.random.seed(0) # ziarno losowania, za kazdym razym uzyskamy ten sam wynik losowania

In [92]:
np.random.randn() # losowa wartosc z rozkladu normalnego

1.764052345967664

In [93]:
np.random.randn(10) # 10 losowo wygenerowanych elementow

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [94]:
np.random.randn(10, 4) # liczba_wierszy, liczba_kolumn

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [95]:
np.random.rand()

0.1965823616800535

In [96]:
np.random.randint(10) # losowa wartosc

0

In [97]:
np.random.randint(low=10, high=100) # losowa liczba z tego zakresu

79

In [98]:
np.random.randint(low=10, high=100, size=10) # size - liczba danych ktore potrzebujemy

array([10, 60, 46, 44, 58, 13, 52, 87, 31, 83])

In [101]:
np.random.choice([4, 3, 4, 6, 7, 9]) # wybiera losowo element z obiektu iterowalnego

4

In [102]:
data = np.arange(10)

In [103]:
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [104]:
np.random.shuffle(data)

In [105]:
data

array([9, 0, 6, 4, 5, 3, 8, 1, 2, 7])

Podstawowe funkcje w bibliotece NumPy


In [106]:
np.exp(1)

2.718281828459045

In [107]:
np.sqrt(4) # pierwiastek kwadratowy

2.0

In [108]:
np.all([3, 0, 1]) # sprawdza wartosc logiczna

False

In [109]:
np.any([3, 0, 1]) # sprawdza czy ktorykolwiek obiekt jest prawda

True

In [110]:
A = np.random.rand(5)

In [111]:
A

array([0.56660145, 0.26538949, 0.52324805, 0.09394051, 0.5759465 ])

In [112]:
np.argmax(A) # funkcja ktora zwroci najwieksza wartosc, indeks elementu z najwieksza wartoscia

4

In [114]:
A[np.argmax(A)]

0.5759464955561793

In [115]:
np.argmin(A)

3

In [116]:
np.argsort(A) # sortowanie wzgledem indeksow

array([3, 1, 2, 0, 4])

In [117]:
np.max(A)

0.5759464955561793

In [118]:
np.min(A)

0.09394051075844168

In [122]:
np.mean(A) # srednia

0.4050252009854683

In [121]:
np.median(A) # mediana

0.5232480534666997

In [123]:
np.std(A) # odchylenie standardowe

0.1926496474978348

In [124]:
#### INDEKSOWANIE I WYCINANIE ####

In [125]:
A = np.arange(20)

In [126]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [127]:
A[2] # element z indeksem drugim

2

In [130]:
A[2:] # od drugiego indeksu do konca

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [129]:
A[:2]

array([0, 1])

In [132]:
A = A.reshape(4, 5)

In [133]:
A[0] # WIERSZ PIERWSZY

array([0, 1, 2, 3, 4])

In [135]:
A[:,0] # PIERWSZA KOLUMNA

array([ 0,  5, 10, 15])

In [136]:
A[:, -1] # OSTATNIA KOLUMNA

array([ 4,  9, 14, 19])

In [137]:
A[1, 1] # KONKRETNY ELEMENT

6

In [138]:
A[1:3, 1:4] # KONKRETNY ZAKRES

array([[ 6,  7,  8],
       [11, 12, 13]])

In [139]:
A[1, 2] = 14 # WSTAWIMY NOWA WARTOSC POD KONKRETNE INDEKSY

In [140]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [141]:
###  Array: Iteracja po tablicach, zmiana rozmiaru oraz maski logiczne


In [142]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [144]:
for row in A: # iterowanie po wierszu
  print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [145]:
for item in A.flat: # iterowanie po kazdym elemencie
  print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


In [146]:
### ZMIANA ROZMIARU TABLIC

In [147]:
A.shape

(4, 5)

In [148]:
A.reshape(5, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [149]:
A.ravel() # wypaszczenie danych

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [150]:
A.T # transponowanie, zamiana wiersza na kolumne, kolumne na wiersz

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [151]:
### MASKI LOGICZNE

In [152]:
A = np.arange(start=-10, stop=10, step=0.5)

In [153]:
A

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,  -5. ,  -4.5,  -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5,
        -1. ,  -0.5,   0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,
         3.5,   4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ,   7.5,
         8. ,   8.5,   9. ,   9.5])

In [154]:
A.reshape(10, -1)

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [155]:
# szukany wartosci ujemnych

In [156]:
A > 0

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

In [157]:
A[A>0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [158]:
np.bitwise_and(A > -5, A < 5) # laczenie warunkow

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False, False, False, False, False,
       False, False, False, False])

In [159]:
A[np.bitwise_and(A > -5, A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [160]:
np.bitwise_or( A < -5, A > 5)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

In [162]:
A[np.bitwise_or( A < -5, A > 5)]

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,   5.5,   6. ,   6.5,   7. ,   7.5,   8. ,   8.5,   9. ,
         9.5])